import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/site/Header";
import { Footer } from "@/components/site/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="zh"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col text-amber-50">
        {/* 全站固定背景图 */}
        <div
          aria-hidden="true"
          className="fixed inset-0 z-0 bg-[url('/images/site-bg.jpg')] bg-cover bg-center"
        />
        {/* 可选：加一层遮罩，文字更清楚 */}
        <div aria-hidden="true" className="fixed inset-0 z-0 bg-black/40" />

        <Header />
        <main> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
